### ISSUE TITLE
Fix mysterious bug in `compute_product`

### ISSUE THREAD

**Issue by dalcde** [hoodmane/rust_ext#41]
`vector_idx` should be `output_module.operation_generator_to_index(0, 0, elt.t, elt.index)`, not `0`. The code is definitely wrong, because `elt.index` is not used anywhere.

**Comment by dalcde** [comment]
Do you have any thoughts on what went wrong with this? I looked over the code multiple times and it looks fine to me.

**Comment by hoodmane** [comment]
Absolutely no clue.

**Comment by dalcde** [comment]
Fixed: https://github.com/hoodmane/rust_ext/commit/93e08252d511513afd55f8174e21a6ef38554109

Being able to resolve up to a specified bidegree helps with debugging a *lot*.

So this is the problem. In `generate_old_kernel...` you first compute the kernel of the differential/chain map when restricted to the elements that come from lower degree. You then proceed to throw away the kernel of that map. This is fine for figuring out which new generators to add, but is not okay when computing quasi-inverses. It is important to remember which of those elements get sent to 0. If we just forget some of the elements in the domain, everything gets messed up because we refer to basis elements by their index.

For example, in degrees `(s, t) = (2, 12)`, there are two basis elements, βP²βa₀² and the new generator that represents β₁. The differential kills βP²βa₀², so everything coming from lower degrees is in the kernel. When we extend our differential to a surjection (dβ₁ = P²h₀), we record the new generator in the first row, because we threw away the kernel. So by the end, we see that the differential is non-zero on the first row, and we think d(βP²βa₀²) is non-zero when computing the quasi-inverse.

So finally, when we compute β₁ * 1, we calculate dβ₁ = P²h₀ correctly (because when we write the matrix to the differentials, we are aware of the fact that we threw away some rows). We apply the chain map, which is the identity, and use the quasi-inverse to find something that hits P²h₀. But the quasi-inverse thinks βP²βa₀² hits P²h₀, and so gives us a wrong answer.

**Comment by hoodmane** [comment]
Well it worked in the C code with the "write over kernel rows" logic, and I'm still not sure why it worked there and didn't work here. But that's a pretty sensible source for the problem.
